version: '3'

services:
  simulator_node:
    context: .
    dockerfile: simulator_node.dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - LIBGL_ALWAYS_INDIRECT=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      # - ROS_MASTER_URI=http://master:11311
      # - ROS_HOSTNAME=simulator_node
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - ros_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]