zed_camera:
  ObjectsStamped: "obj_det/objects"
  RGBDSensors: "rgbd_sens"
  PlaneStamped: "plane"
  Marker: "plane_marker"


pose:
  Pose: "/rexrov2/pose_gt"

dvl:
  DVL_Message: "/wayfinder/topic_name"

imu:
  yaw: "/hydrus/IMU/yaw"
  pitch: "/hydrus/IMU/pitch"
  roll: "/hydrus/IMU/roll"

uuv_control_services:
  GoTo: "/your_goto_service"
  Hold: "/rexrov2/hold_vehicle"
